apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki-desenvolvimento
      app.kubernetes.io/component: logging
      app.kubernetes.io/part-of: observability
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/environment: desenvolvimento
    includeSelectors: false

patches:
  - target:
      group: loki.grafana.com
      version: v1
      kind: LokiStack
      name: loki
      namespace: openshift-logging
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: crc-csi-hostpath-provisioner
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: minio-data
      namespace: openshift-logging
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: crc-csi-hostpath-provisioner
