apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: loki
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  size: 1x.demo
  storageClassName: crc-csi-hostpath-provisioner
  storage:
    secret:
      name: loki-s3
      type: s3
    schemas:
      - version: v13
        effectiveDate: "2024-01-01"
  tenants:
    mode: openshift-logging
