apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-password
            - name: HOME
              value: /tmp
            - name: MC_CONFIG_DIR
              value: /tmp/.mc
          command: ["/bin/sh","-lc"]
          args:
            - |
              set -e
              until mc alias set local http://minio.openshift-logging.svc:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"; do
                echo "waiting minio..."
                sleep 3
              done
              mc mb -p local/loki || true
              mc ls local/loki
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
