apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: crc-csi-hostpath-provisioner
