apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: loki
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  size: 1x.small
  storageClassName: crc-csi-hostpath-provisioner
  storage:
    schemas:
      - version: v13
        effectiveDate: "2024-01-01"
    storageClassName: crc-csi-hostpath-provisioner
  tenants:
    mode: openshift-logging
