apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: loki-operator
  namespace: openshift-operators-redhat
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  name: loki-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: stable-6.4
  installPlanApproval: Automatic
